INSERT INTO usuario(cod_registro, nombre, password,habilitado,correo) VALUES ('open123', 'David Villca','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',true, 'davidVillca@gmail.com');
INSERT INTO usuario(cod_registro, nombre, password,habilitado,correo) VALUES ('open456', 'Kevin Vargas','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',true, 'kevinVargasa@gmail.com');
INSERT INTO usuario(cod_registro, nombre, password,habilitado,correo) VALUES ('open789', 'Mijael Mijael','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',true, 'mijaelMijale@gmail.com');
INSERT INTO usuario(cod_registro, nombre, password,habilitado,correo) VALUES ('open321', 'Jorge Jorge','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',true, 'jorgeJorgea@gmail.com');
INSERT INTO rol(tipo) VALUES ('ROLE_ADMIN');
INSERT INTO rol(tipo) VALUES ('ROLE_COMMISSION');
INSERT INTO rol(tipo) VALUES ('ROLE_JURY');
INSERT INTO rol(tipo) VALUES ('ROLE_LEADER');
INSERT INTO rol(tipo) VALUES ('ROLE_LEADER_GROUP');
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open123',1);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open456',1);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open123',2);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open456',2);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open123',3);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open789',3);
INSERT INTO usuario_rol(usuario_cod_registro, rol_id_rol) VALUES('open321',4);
